---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    vault:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - vault://secret/kc
  cloud:
    vault:
      token: ${image-vault-token}
      scheme: http
      host: vault
      port: 8200
      kv:
        enabled: true
        backend: secret
        profiles: